workspace:
  base: /vue
  path: src/github.com/readr-media/readr-site
pipeline:
  start_slack:
    image: plugins/slack
    channel: jenkins
    secrets: [slack_webhook]
    username: drone
    icon_url: https://avatars2.githubusercontent.com/u/2181346?s=200&v=4
    template: >
      *start* building *{{repo.name}}* <${DRONE_BUILD_LINK}|#{{build.number}}>.
      Someone gave *{{build.branch}}* a little push.
    when:
      event: [push]
  
  get_dev_config:
    image: gcr.io/mirrormedia-1470651750304/drone-cloud-sdk:latest
    secrets: [google_credentials]
    commands:
    - gcloud source repos clone default default
    - cp default/readr-site/config.js api/
    - cp default/readr-site/gcskeyfile.json ./gcskeyfile.json
    when:
      event: [push]
      branch: [dev]
  get_prod_config:
    image: gcr.io/mirrormedia-1470651750304/drone-cloud-sdk:latest
    secrets: [google_credentials]
    commands:
    - gcloud source repos clone default default
    - cp default/readr-site/config.js api/
    - cp default/readr-site/gcskeyfile.json ./gcskeyfile.json
    when:
      event: [push]
      branch: [master, stage]
  builds:
    image: node:9.2.0-alpine
    commands:
    - apk update
    - apk add vips-dev fftw-dev --update-cache --repository https://dl-3.alpinelinux.org/alpine/edge/testing/
    - apk add --no-cache python build-base make
    - yarn install
    - yarn run build
    when:
      event: [push]
      branch: [master, dev, stage]

  publish:
    image: plugins/gcr
    repo: mirrormedia-1470651750304/${DRONE_REPO_NAME}
    tag: ${DRONE_COMMIT_AUTHOR}_${DRONE_COMMIT_BRANCH}_${DRONE_BUILD_NUMBER}
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    secrets: [google_credentials]
    when:
      event: [push]
      branch: [master, dev, stage]
  
  deploy_dev:
    image: nytimes/drone-gke:develop
    zone: asia-east1-a
    cluster: dev
    namespace: default
    # For debugging
    dry_run: false
    verbose: true
    secrets:
      - source: google_credentials
        target: token
    vars:
      image: gcr.io/mirrormedia-1470651750304/${DRONE_REPO_NAME}:${DRONE_COMMIT_AUTHOR}_${DRONE_COMMIT_BRANCH}_${DRONE_BUILD_NUMBER}
      app: ${DRONE_REPO_NAME}
      tier: frontend
    when:
      event: [push]
      branch: dev
  
  deploy_stage:
    image: nytimes/drone-gke:develop
    zone: asia-east1-a
    cluster: readr-prod
    namespace: default
    # For debugging
    dry_run: false
    verbose: true
    secrets:
      - source: google_credentials
        target: token
    vars:
      image: gcr.io/mirrormedia-1470651750304/${DRONE_REPO_NAME}:${DRONE_COMMIT_AUTHOR}_${DRONE_COMMIT_BRANCH}_${DRONE_BUILD_NUMBER}
      app: ${DRONE_REPO_NAME}
      tier: frontend
    when:
      event: [push]
      branch: stage

  finish_slack:
    image: plugins/slack
    channel: jenkins
    secrets: [slack_webhook]
    username: drone
    icon_url: https://avatars2.githubusercontent.com/u/2181346?s=200&v=4
    when:
      status: [success, failure]
      event: [push]
    template: >
      {{#success build.status}}
        *success* ${DRONE_REPO_NAME}:${DRONE_COMMIT_AUTHOR}_${DRONE_COMMIT_BRANCH}_${DRONE_BUILD_NUMBER} was well served.
        Check out our new <https://dev.readr.tw|readr>.
      {{else}}
        Houston, we have a problem. Build <${DRONE_BUILD_LINK}|#{{build.number}}> failed.
      {{/success}}