const supertest = require('supertest')

const api = supertest('http://localhost:8080')
const chai = require('chai')
const should = chai.should()

describe('test member data fetching', () => {
  it('should get member data from api', (done) => {
    api.get('/api/member/abc1231')
    .end(function(err, res) {
      if (err) return console.log(err)
      res.body.should.be.an('object').and.have.property('id')
      res.body.should.have.property('name')
      res.body.should.have.property('nickname')
      res.body.should.have.property('birthday')
      res.body.should.have.property('gender')
      res.body.should.have.property('occupation')
      res.body.should.have.property('mail')
      res.body.should.have.property('register_mode')
      res.body.should.have.property('social_id')
      res.body.should.have.property('created_at')
      res.body.should.have.property('updated_at')
      res.body.should.have.property('updated_by')
      res.body.should.have.property('description')
      res.body.should.have.property('profile_image')
      res.body.should.have.property('identity')
      res.body.should.have.property('custom_editor')
      res.body.should.have.property('hide_profile')
      res.body.should.have.property('profile_push')
      res.body.should.have.property('post_push')
      res.body.should.have.property('comment_push')
      res.body.should.have.property('active')
      done()
    })
  })
})
