import projectList from './projectList'
export const PROJECTS = projectList

export const SITE_DOMAIN = 'readr.com'

export const WORDING_EMAIL = '信箱'
export const WORDING_FORGET_PASSWORD = '忘記密碼？'
export const WORDING_KEEP_ALIVE = '保持登入'
export const WORDING_LOGIN = '登入'
export const WORDING_LOGIN_COMMUNITY = '社群登入'
export const WORDING_LOGIN_INFAIL_VALIDATION_ISSUE = '請提供正確帳號密碼。'
export const WORDING_MEMBER_AGREEMENT = '會員服務協議'
export const WORDING_NICKNAME = '暱稱'
export const WORDING_PASSWORD = '密碼'
export const WORDING_PASSWORD_CHECK = '確認密碼'
export const WORDING_REGISTER = '註冊'
export const WORDING_REGISTER_EMAIL_VALIDATE_IN_FAIL = '請輸入有效的電子信箱（Email）'
export const WORDING_REGISTER_NICKNAME_EMPTY = '請輸入暱稱'
export const WORDING_REGISTER_NOTICE = '註冊會員等同您同意我們的'
export const WORDING_REGISTER_SUCESSFUL = '請至您註冊的 Email 信箱點擊啟用連結'
export const WORDING_REGISTER_INFAIL = '註冊過程發生問題，請聯絡我們'
export const WORDING_REGISTER_INFAIL_DUPLICATED = '該電子信箱（Email）已被使用，請改用其他電子信箱。'
export const WORDING_REGISTER_PWD_EMPTY = '請輸入密碼'
export const WORDING_REGISTER_PWD_CHECK_EMPTY = '請再次輸入密碼'
export const WORDING_REGISTER_PWD_CHECK_INFAIL = '「密碼」與「確認密碼」不同，請輸入相同之密碼'
export const WORDING_FACEBOOK_LOGIN = '使用 Facebook 帳號登入'
export const WORDING_FACEBOOK_REGISTER = '使用 Facebook 帳號註冊'
export const WORDING_GOOGLE_LOGIN = '使用 Google 帳號登入'
export const WORDING_GOOGLE_REGISTER = '使用 Google 帳號註冊'
